language: ruby
os: osx
rvm: system

before_install:
  - brew update || brew update
  - export HOMEBREW_DEVELOPER="1"
install:
  - brew tap chigraph/kf5 file://$PWD
script:
  - brew install chigraph/kf5/kf5-karchive
